### ISSUE TITLE
how to Compress

### ISSUE THREAD

**Issue by emtry** [emn178/js-sha512#13]

**Comment by dosisod** [comment]
You will have to compress it yourself, I would recommend using `minify` from `npm`:
```
$ npm install -g minify
$ minify sha512.js > sha512.min.js
```
Before and after:
```
-rw-r--r--  1 noot noot  36K Dec  3 21:57 sha512.js
-rw-r--r--  1 noot noot  18K Dec  3 22:05 sha512.min.js
```

**Comment by dosisod** [comment]
Edit: Look at README for link to [minified file](https://raw.github.com/emn178/js-sha512/master/build/sha512.min.js)

**Comment by emtry** [comment]
thx
