### ISSUE TITLE
Allow continuing a hash after getting a readout

### ISSUE THREAD

**Issue by qm3ster** [emn178/js-sha512#6]
## Feature request

1. Make the `.finalize()` not mutate the object, so that you can `.arrayBuffer()` to get a digest but then continue `.update()`-ing the same hash.
2. If this has a measurable performance/memory use impact, make this an option on the constructor or the finalize function, so that those who don't need it don't get affected.
3. Cache the finalization and invalidate it only when updating, so that `h.hex(); h.arrayBuffer(); h.hex(); h.arrayBuffer(); h.update();` only carries out the finalization process once.

**Comment by emn178** [comment]
1. you want to get `arrayBuffer` or other outputs but not execute `finalize()`?
3. invalidate it means rollback to before finalization?

**Comment by qm3ster** [comment]
1. No, I want to execute it, so I can get a spec compliant hash for the stream so far, but then continue.
2. Yes. You could clone the buffer before finalization, or, more performantly, rewind it to cut off the padding, if I understand correctly.

**Comment by emn178** [comment]
I see. What you want is something like this
```JavaScript
var hash = sha512.update('a');
hash.hex();

hash.update('b'); // continue hash
hash.hex(); // equal to sha512('ab');
```

**Comment by qm3ster** [comment]
Yup, that would be a good API.

**Comment by emn178** [comment]
v0.8.0 added `clone()` method, you can do following now.
```JavaScript
var hash = sha512.update('a');
hash.clone().hex();

hash.update('b'); // continue hash
hash.hex(); // equal to sha512('ab');
```
