### ISSUE TITLE
Report update progress

### ISSUE THREAD

**Issue by qm3ster** [emn178/js-sha512#7]
## Feature request

1. Take a callback in the update function/constructor. Call it once in a few blocks with some format of progress on the current input.
2. If this has a measurable performance/memory use impact, make this an option on the constructor, so that those who don't need it don't get affected.

**Comment by emn178** [comment]
You can handle progress from outside, looks this demo.
http://emn178.github.io/online-tools/sha256_checksum.html

the source code
https://github.com/emn178/online-tools/blob/master/js/main.js#L74-L88

this is sha256 demo but sha512 is similar.

**Comment by qm3ster** [comment]
That's really smooth.
I wish I found that repo/page before I implemented the same thing using spec documentation.
I guess I could do that.
I was just using 64MB chunks, so the progress reporting was coarse.
Is there no performance impact from such small chunks?

**Comment by emn178** [comment]
I think that it should lose some performance. But I didn't experiment. Maybe you can do some benchmark.

**Comment by qm3ster** [comment]
I found out that it was very efficient, especially if I call async read of the next chunk before I `.update()` with the ready one. Satisfies my use case completely.
