### ISSUE TITLE
How to unhash?

### ISSUE THREAD

**Issue by TehRealShot** [emn178/js-sha512#9]
Is there a way to get the original message after it is hashed?
ex:
`
var hashed = sha512.hmac('key', 'Message to hash');
var unhashed = sha512.unhmac('key', '840fd9766d83b57f06eead2bba0d4632b7dfad8f3645d9e4c70cce68c309f996f45d6e3d904f2acda0f2e84da8d8970429624622b9001cddb9f5f7c5a6506b0a');
`

**Comment by CampNowhere** [comment]
No, that is the point of a hash function - it is hard to determine the input value of any given hash. And your code is not a hash function, it is a Hash-based message authentication code.

**Comment by TehRealShot** [comment]
Even if i have the key?
